#!/usr/bin/env python3
"""Embed a PhyWear Markdown Skill into a C string array.

The skill files under apps/examples/phywear/skills/ are the single source of
truth.  PhyWear installs them into /data/agent/skills/ at startup so that the
AI Agent finds them on any target, including the real Huangshan Pi board whose
/data is a tmpfs that is empty after every boot.

This script regenerates apps/examples/phywear/pw_skill_blob.c from the .md
files.  Run it after editing a skill:

    tools/phywear/gen_skill_blob.py

gen_skill_blob.py --check regenerates into memory and fails if the checked-in
copy is stale, so drift is caught in tests.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SKILL_DIR = os.path.join(ROOT, "apps", "examples", "phywear", "skills")
OUT = os.path.join(ROOT, "apps", "examples", "phywear", "pw_skill_blob.c")

BANNER = """/* %s
 *
 * Generated by tools/phywear/gen_skill_blob.py -- do not edit by hand.
 * Source: apps/examples/phywear/skills/%s
 */

#include "pw_skill.h"

const char %s[] =
"""

HEX = "0123456789abcdefABCDEF"


def c_ident(filename):
    return "g_pw_skill_" + filename[:-3].replace("-", "_")


def tokenize(data):
    """Return the C tokens for the data, keeping \\xNN escapes unambiguous."""

    parts = []
    prev_escape = False
    for byte in data:
        if byte == 0x0A:
            tok, escape = "\\n", False
        elif byte == 0x09:
            tok, escape = "\\t", False
        elif byte == 0x22:
            tok, escape = "\\\"", False
        elif byte == 0x5C:
            tok, escape = "\\\\", False
        elif 0x20 <= byte < 0x7F:
            tok, escape = chr(byte), False
        else:
            tok, escape = "\\x%02x" % byte, True

        # "a\x86b" would be read as one escape \x86b; break the literal.
        if prev_escape and tok[0] in HEX:
            parts.append('" "')
        parts.append(tok)
        prev_escape = escape
    return parts


def emit(path, out):
    with open(path, "rb") as fh:
        data = fh.read()

    src = os.path.basename(path)
    out.write(BANNER % ("*" * 74, src, c_ident(src)))

    line = ""
    for tok in tokenize(data):
        if len(line) + len(tok) > 92:
            out.write('  "%s"\n' % line)
            line = ""
        line += tok
    out.write('  "%s";\n\n' % line)


def render():
    skills = sorted(f for f in os.listdir(SKILL_DIR) if f.endswith(".md"))
    if not skills:
        sys.exit("no .md skills found in %s" % SKILL_DIR)

    chunks = []
    for src in skills:
        import io
        buf = io.StringIO()
        emit(os.path.join(SKILL_DIR, src), buf)
        chunks.append(buf.getvalue())
    return "".join(chunks), skills


def main():
    text, skills = render()

    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            sys.exit("missing %s" % OUT)
        with open(OUT, encoding="ascii") as fh:
            if fh.read() != text:
                sys.exit("STALE: %s does not match the .md skills; rerun "
                         "tools/phywear/gen_skill_blob.py" % OUT)
        print("ok: %s matches %d skill(s)" % (OUT, len(skills)))
        return

    with open(OUT, "w", encoding="ascii") as out:
        out.write(text)
    print("wrote %s (%d skill(s): %s)" % (OUT, len(skills), ", ".join(skills)))


if __name__ == "__main__":
    main()
